# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_development
  username: postgres
  password: kandy


test:
  <<: *default
  database: hello_rails_test
  username: postgres
  password: kandy


production:
  <<: *default
  database: hello_rails_production
  username: postgres
  password: kandy
